# -*- coding: utf-8 -*-
"""langchain_agent_sql_to_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1gKexbKGLOaVrFEgT-x0tV5DOS3nGxJ
"""

!pip install langchain langchainhub langchain_openai openai

from langchain.sql_database import SQLDatabase
from langchain_openai import ChatOpenAI
from langchain.schema.output_parser import StrOutputParser
from langchain import hub
from google.colab import userdata
from langchain_community.agent_toolkits import create_sql_agent


secret_string = userdata.get('OPENAI_TOKEN')

# Inicializamos db
db = SQLDatabase.from_uri("sqlite:///Chinook_Sqlite.sqlite")

llm = ChatOpenAI(openai_api_key=secret_string, model="gpt-4", temperature=0)

agent_executor = create_sql_agent(llm, db=db, agent_type="openai-tools", verbose=True)
resultado = agent_executor.invoke(
    "Give me the name of five of your employees with their address"
)
print(resultado.get('output'))